export { Hero } from "./Hero";
export { Stats } from "./Stats";
export { About } from "./About";
export { Benefits } from "./Benefits";
export { Philosophy } from "./Philosophy";
export { Collection } from "./Collection";
export { Details } from "./Details";
export { CTA } from "./CTA";
export { Footer } from "./Footer";
